name: terminal-portfolio

services:
  # Development service (default profile)
  dev:
    build:
      context: .
      target: dev
    command: pnpm dev
    ports:
      - "5173:5173" # Vite's default port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_CONFIG_GIST_URL=${VITE_CONFIG_GIST_URL}
    profiles: ["dev"]
    # Enable hot reload
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./pnpm-lock.yaml
          action: rebuild

  # Production service
  prod:
    build:
      context: .
      target: production
    ports:
      - "5080:80"
    environment:
      - NODE_ENV=production
      - VITE_CONFIG_GIST_URL=${VITE_CONFIG_GIST_URL}
    profiles: ["prod"]
    restart: unless-stopped

# Set default profile to dev
x-profiles:
  dev: true
